#!/usr/bin/python3
# -*- coding: utf-8 -*-
translation_dic = {'hnd': 'E.Honda',
                   'urn': 'Urien',
                   'blr': 'CLAW',
                   'veg': 'DICTATOR',
                   'blk': 'Blanka',
                   'bsn': 'BOXER',
                   'dsm': 'Dhalsim',
                   'ed': 'Edd',
                   'brd': 'Birdie',
                   'abg': 'Abigail',
                   'flk': 'Falke',
                   'alx': 'Alex',
                   'gul': 'Guile',
                   'fan': 'FANG',
                   'g': 'G',
                   'cdy': 'Cody',
                   'zgf': 'Zangief',
                   'psn': 'Poison',
                   'zku': 'Zeku',
                   'lar': 'Laura',
                   'krn': 'Karin',
                   'sgt': 'Sagat',
                   'nsh': 'Nash',
                   'ncl': 'Necalli',
                   'lca': 'Lucia',
                   'ibk': 'Ibuki',
                   'gil': 'Gill',
                   'kln': 'Kolin',
                   'cnl': 'ChunLi',
                   'jri': 'Juri',
                   'ryu': 'Ryu',
                   'sth': 'Seth',
                   'ken': 'Ken',
                   'kge': 'Kage',
                   'rmk': 'R.Mika',
                   'cmy': 'Cammy',
                   'skr': 'Sakura',
                   'mnt': 'Menat',
                   'gok': 'Akuma',
                   'rsd': 'Rashid',
                   'dan': 'Dan',
                   'rse': 'Rose'
                   }
